print("ฬєɭς0๓є Շгคשєɭ3г")
input()
a=input("𝙿𝚕𝚎𝚊𝚜𝚎 𝚒𝚗𝚝𝚛𝚘𝚍𝚞𝚌𝚎 𝚢𝚘𝚞𝚛 𝚗𝚊𝚖𝚎:")
input()
print("Hell0",a)
input()
print("Lets begin")
input()
print("´You are in your r00m finishing a sch00l pr0ject´")
input()
print("M0m:",a,"dinner´s ready c0me d0wnstairs!")
input()
print(a,": C0ming m0m!")
input()
print("´Y0u g0 d0wnstairs and take a sit while y0ur m0m serves y0u f00d´")
input()
print(a,": S00 m0m ab0ut the summer camp...")
input()
print("M0m:",a,"We already talked ab0ut this, y0ur dad and i are busy that day, why d0n´t y0u wait f0r next summer?")
input()
print(a,": But m0m all my friends are g0ing t0 the camp this summer!")
input()
print("M0m: Well y0u can ask them f0r ph0tos when the camp is 0ver ")
input()
print(a,": N0t funny m0m")
input()
print("M0m: Why d0n´t y0u eat and we discuss this later with y0ur dad?")
input()
print(a,": I´m n0t hungry, thank y0u")
input()
print("´Y0u get up and walk towards the d00r´")
input()
print("M0m: Where are y0u g0ing?")
input()
print(a,": Just t0 take s0me air and think, i w0n´t take l0ng i swear")
input()
print("M0m: 0k but y0u gotta be home by 9:00pm")
input()
print(a,": 0k m0m")
input()
print("´Y0u get 0ut and start walking int0 the f0rest near y0ur h0use´")
input()
print(a,": Why are they always like that, they always find a way to ruin my vacati0ns")
input()
print("´Y0u hear s0mething´")
input()
print(a,": Wh0´s there?")
input()
print("´ₘₒᵣₑ wₑᵢᵣd ₙ₀ᵢₛₑₛ´")
input()
print("´Y0u feel s0me0ne hit y0u 0n the head")
input()
print("´ₑᵥₑᵣyₜₕᵢₙg ₜᵤᵣₙₛ bₗₐcₖ´")
input()
r=1
while (r<=20):
  print(".... . .-.. .--.01110000 01101100 01100101 01100001 01110011 01100101 00100000 01101000 01100101 01101100 01110000.... . .-.. .--.")
  r=r+1

input()
print("´Y0u wake up´")
input()
print("?: Hell0 sleepy head, did you sleep well?")
input()
print(a,": WH0 ARE YOU?!")
input()
print("?: W0ah w0ah calm d0wn")
input()
print(a,": Y0U WANT ME TO CALM DOWN?! WHAT THE HELL IS THIS PLACE?! WHERE AM I?!!")
input()
print("?: Yeah let´s say y0u´re n0t home")
input()
print(a,": What d0 y0u mean with i´m n0t h0me?")
input()
print("?: Yeah, and i´m Charles by the way")
input()
print("´ⁿᵉʷ ᶠʳ?ᵉⁿᵈ ᵘⁿˡᵒᶜᵏᵉᵈ?´")