#Nivel uno: Pau
print("ฬєɭς0๓є Շгคשєɭ3г")
input()
a = input("𝙿𝚕𝚎𝚊𝚜𝚎 𝚒𝚗𝚝𝚛𝚘𝚍𝚞𝚌𝚎 𝚢𝚘𝚞𝚛 𝚗𝚊𝚖𝚎:")
input()
print("Hell0", a)
input()
print("Lets begin")
input()
print("´You are in your r00m finishing a sch00l pr0ject´")
input()
print("M0m:", a, "dinner´s ready c0me d0wnstairs!")
input()
print(a, ": C0ming m0m!")
input()
print("´Y0u g0 d0wnstairs and take a sit while y0ur m0m serves y0u f00d´")
input()
print(a, ": S00 m0m ab0ut the summer camp...")
input()
print(
    "M0m:", a,
    "We already talked ab0ut this, y0ur dad and i are busy that day, why d0n´t y0u wait f0r next summer?"
)
input()
print(a, ": But m0m all my friends are g0ing t0 the camp this summer!")
input()
print("M0m: Well y0u can ask them f0r ph0tos when the camp is 0ver ")
input()
print(a, ": N0t funny m0m")
input()
print("M0m: Why d0n´t y0u eat and we discuss this later with y0ur dad?")
input()
print(a, ": I´m n0t hungry, thank y0u")
input()
print("´Y0u get up and walk towards the d00r´")
input()
print("M0m: Where are y0u g0ing?")
input()
print(a, ": Just t0 take s0me air and think, i w0n´t take l0ng i swear")
input()
print("M0m: 0k but y0u gotta be home by 9:00pm")
input()
print(a, ": 0k m0m")
input()
print("´Y0u get 0ut and start walking int0 the f0rest near y0ur h0use´")
input()
print(
    a,
    ": Why are they always like that, they always find a way to ruin my vacati0ns"
)
input()
print("´Y0u hear s0mething´")
input()
print(a, ": Wh0´s there?")
input()
print("´ₘₒᵣₑ wₑᵢᵣd ₙ₀ᵢₛₑₛ´")
input()
print("´Y0u feel s0me0ne hit y0u 0n the head")
input()
print("´ₑᵥₑᵣyₜₕᵢₙg ₜᵤᵣₙₛ bₗₐcₖ´")
input()
r = 1
while (r <= 20):
    print(
        ".... . .-.. .--.01110000 01101100 01100101 01100001 01110011 01100101 00100000 01101000 01100101 01101100 01110000.... . .-.. .--."
    )
    r = r + 1

input()
print("´Y0u wake up´")
input()
print("?: Hell0 sleepy head, did you sleep well?")
input()
print(a, ": WH0 ARE YOU?!")
input()
print("?: W0ah w0ah calm d0wn")
input()
print(
    a,
    ": Y0U WANT ME TO CALM DOWN?! WHAT THE HELL IS THIS PLACE?! WHERE AM I?!!")
input()
print("?: Yeah let´s say y0u´re n0t home")
input()
print(a, ": What d0 y0u mean with i´m n0t h0me?")
input()
print("?: Yeah, and i´m Charles by the way")
input()
print("´ⁿᵉʷ ᶠʳ?ᵉⁿᵈ ᵘⁿˡᵒᶜᵏᵉᵈ?´")

#Nivel dos: Ros
print("congrats")
input()
print("you made it")
input()
print("...")
input()
print("            ᴼʳ ᵈⁱᵈ ʸᵒᵘ")
input()
r = 1
while (r <= 20):
    print("AႱAႱAႱႱAႱAႱAႱႱAႱAႱAႱAႱA")
    r = r + 1

input()
print("*you wake up scared of what just happend*")
input()
print("*but you woke up in a room you dont know*")
input()
print("*you dont remember how you got there*")
input()
print(".....")
input()
print("*and neither your name..*")
input()
print("__:hello?")
input()
print("            𝗦𝗶𝗹𝗲𝗻𝗰𝗲")
input()
print(".....")
input()
print("𝘏𝘪 𝘐 𝘴𝘦 𝘺𝘰𝘶 𝘧𝘪𝘯𝘢𝘭𝘭𝘺 𝘸𝘰𝘬𝘦 𝘶𝘱")
input()
print("__:umm hi?")
input()
print("__:WHO ARE YOU")
input()
print("𝘋𝘰𝘯’𝘵 𝘸𝘰𝘳𝘳𝘺")
input()
print("__:who am i?")
input()
a = input("𝘾𝙝𝙤𝙤𝙨𝙚 𝙮𝙤𝙪𝙧 𝙣𝙖𝙢𝙚:")
input()
print("𝘠𝘰𝘶𝘳 𝘯𝘢𝘮𝘦 𝘪𝘴", a)
input()
print(a, ":mm i am not sure but i like it")
input()
print("*your head starts to hurt*")
input()
e = 1
while (e <= 20):
    print("ᗩᐯEᖇY")
    e = e + 1

input()
print(a, ":avery")
input()
print("𝘞𝘩𝘢𝘵 𝘸𝘢𝘴 𝘵𝘩𝘢𝘵?")
input()
print("ᴄʜᴏᴏꜱᴇ ᴀɴ ᴏᴘᴛɪᴏɴ ᴛᴏ ʟɪᴇ ᴏʀ ɴᴏᴛ")
input()
print("a) dont tell him")
print("b) tell him")
input()
s = input("ᴄʜᴏᴏꜱᴇ ᴀɴ ᴏᴘᴛɪᴏɴ:")
input()

if (s == 'a'):
    print(a, ":mm nothing , i am just hungry")
    input()
    print("𝘖𝘩 𝘺𝘦𝘢𝘩 𝘵𝘩𝘦𝘳𝘦’𝘴 𝘧𝘰𝘰𝘥 𝘭𝘦𝘵 𝘮𝘦 𝘴𝘩𝘰𝘸 𝘺𝘰𝘶")
    input()
    print("*you follow him*")
    input()
    print("𝘏𝘦𝘳𝘦 𝘪𝘴 𝘵𝘩𝘦 𝘧𝘰𝘰𝘥")
    input()
    print(a, ":thanks")
    input()
    print("ʏᴏᴜ ᴊᴜꜱᴛ ᴄʜᴀʀɢᴇ ʏᴏᴜʀ ᴇɴᴇʀɢʏ")
    input()
    print("btw you haven't said your name?")
    input()
    print("𝘐 𝘢𝘮...")

if (s == 'b'):
    print(
        a,
        ":it's just that i remeber a name or last name avery do you know it?")
    input()
    print("𝘐 𝘩𝘢𝘷𝘦 𝘩𝘦𝘢𝘳𝘥 𝘪𝘵")
    input()
    print(a, ":mm ok bueno temgo hambre")
    input()
    print("𝘺𝘰 𝘪𝘨𝘶𝘢𝘭..,𝘮𝘪𝘳𝘢 ahí 𝘩𝘢𝘺 𝘤𝘰𝘮𝘪𝘥𝘢")
    input()
    print("vamos pero primero cual es tu nombre no me haz dicho")
    input()
    print("𝘐 𝘢𝘮...")

#Nivel tres: Ana Pau
print("Welcome.........")
input()
print("You made it....... congratulations")
input()
print("You have come so far, but there is so much left..........")
input()
print("Are you ready?.......")
input()
print("Let's start then......")
input()
print("You are in dark place, you have just woke up")
input()
print("You see a light at a corner of the room")
input()
print("You got up, and walked over to the corner")
input()
print("You found its a computer with something in it")
input()
print("ʜ ᴇ ʟ ʟ ᴏ , ᴘ ʟ ᴇ ᴀ ꜱ ᴇ   ᴇ ɴ ᴛ ᴇ ʀ   ʏ ᴏ ᴜ ʀ   ɴ ᴀ ᴍ ᴇ")
input()
a = input("Please write your name: ")
input()
print("You see that the computer starts to write a lot of numbers in the screen ")
c = 0
while c <= 40:
    print(c)
    c = c + 1
input()
print(a, ": What just happen?")
input()
print(a, ": Where am I?")
input()
print("???: That is a great question, isn't it?")
input()
print("???: Do you know why are you here?")
input()
print(a, ": I....I don´t know")
input()
print(a, ": But, who are you?")
input()
print("???: So.... you don´t remember me")
input()
print("She sounded sad saying this last thing, so you start thinking, do you know this girl?, actually you start to recognize that you don´t remember anything....except for your name")
input()
print(a, ": Who are you?")
input()
print("You asked again starting to feel a little tired for not getting a real answer")
input()
print("???: My name is Emily, and don´t worry I will help you to remember everything")
input()
print("Emily: But you need to get out of this place")
input()
print("You open your eyes and see that the last thing was all a dream, you see that you are in a classroom ")
input()
print("At the front of the classroom was a board with some notes in it")
input()
print("Most of the notes were only words that didn't make sense at all")
input()
print("But there was one note that was important")
input()
print(
    "ɴᴏᴛᴇ: ʜɪ, ʏᴏᴜ ᴍᴏꜱᴛ ʜᴀᴠᴇ ᴡᴀᴋᴇ ᴜᴘ ᴀᴛ ᴛʜɪꜱ ᴘᴏɪɴᴛ ꜱᴏ, ɪ'ᴍ ᴇᴍɪʟʏ ᴛʜᴇ ɢɪʀʟ ꜰʀᴏᴍ ʏᴏᴜʀ ᴅʀᴇᴀᴍꜱ, ɪ ᴀᴍ ɢᴏɴɴᴀ ʜᴇʟᴘ ʏᴏᴜ ɢᴇᴛ ᴏᴜᴛ ᴏꜰ ʜᴇʀᴇ ʙᴜᴛ ʏᴏᴜ ɴᴇᴇᴅ ᴛᴏ ᴅᴏ ᴍᴏꜱᴛ ᴏꜰ ᴛʜᴇ ᴛʜɪɴɢꜱ. ɪ ᴄᴀɴ ᴄᴏᴍᴍᴜɴɪᴄᴀᴛᴇ ᴡɪᴛʜ ʏᴏᴜ ɪɴ ʏᴏᴜʀ ᴅʀᴇᴀᴍꜱ, ꜱᴏ ᴏᴜᴛꜱɪᴅᴇ ᴏꜰ ᴛʜᴇᴍ ᴛʜᴇʀᴇ ɪꜱ ɴᴏᴛ ᴀ ʟᴏᴛ ᴏꜰ ᴛʜɪɴɢꜱ ᴛʜᴀᴛ ɪ ᴄᴏᴜʟᴅ ᴅᴏ, ʙᴜᴛ ɪ ᴡᴏᴜʟᴅ ᴛʀʏ ᴛᴏ ʜᴇʟᴘ ʏᴏᴜ ᴀꜱ ᴍᴜᴄʜ ᴀꜱ ɪ ᴄᴀɴ. ɢᴇᴛ ᴏᴜᴛ ᴏꜰ ᴛʜᴇ ᴄʟᴀꜱꜱʀᴏᴏᴍ ᴀɴᴅ ɢᴏ ᴛᴏ ᴛʜᴇ ʟᴇꜰᴛ ᴘᴀʀᴛ ᴏꜰ ᴛʜᴇ ʙᴜɪʟᴅɪɴɢ, ᴛʜᴇʀᴇ ʏᴏᴜ ᴡɪʟʟ ꜰɪɴᴅ ꜱᴏᴍᴇ ᴅᴏᴄᴜᴍᴇɴᴛꜱ ᴛʜᴀᴛ ʜᴀᴠᴇ ɪɴꜰᴏʀᴍᴀᴛɪᴏɴ ᴀʙᴏᴜᴛ ʏᴏᴜ, ɪ ᴡɪꜱʜ ʏᴏᴜ ᴛʜᴇ ʙᴇꜱᴛ, ᴇᴍɪʟʏ")
input()
print( "After you read the note, you got out of the building, but you asked yourself what would happen if you go to the right part of the building instead")
input()
print("You have to take a decision")
input()
y = input("What do you choose, right or left?, (please all in lower letters) ")
input()
if (y == "right"):
    print(a, ": I think I choose the right side , what is the worst that could happen")
    input()
    print("You walked through a dark corridor, you see other classrooms doors")
    input()
    print(a, ": What is this place? I wonder if I could open one of this doors")
    input()
    print("You see a dark door that looks very old and really strange")
    input()
    x = input("Do you wanna open the door? (write your answer in lower letters)")
    input()
    if (x == "yes"):
        print(a, ": I wonder what is behind this door")
        input()
        print("You open the door and see around the classroom")
        input()
        print("You found a note")
        input()
        print(a, ": What is this note? ")
        input()
        print(
            "ɴᴏᴛᴇ: ᴍᴀʀᴄʜ 23 2014, ᴡʜᴀᴛ ʜᴀᴠᴇ ɪ ᴅᴏɴᴇ, ɪ ꜱʜᴏᴜʟᴅɴ'ᴛ ʜᴀᴠᴇ ᴅᴏɴᴇ ᴛʜɪꜱ, ɪ ᴊᴜꜱᴛ ʜᴏᴘᴇ ᴛʜɪꜱ ᴅᴏᴇꜱɴᴛ ɢᴇᴛ ᴡᴏʀꜱᴇ")
        input()
        print("You keep the note in your pocket")
        input()
        print("And you go out of the classroom and go out of it")
    if (x == "no"):
        print("You just follow the corridor")
    input()
    print("You follow the corridor what seem like hours")
    input()
    print(a, ": What is this place, it seems to big for being a simple school")
    input()
    print( "You follow the corridor, and you find a place that has a big poster")
    input()
    print("ᴍᴀʀᴛᴇꜱ ᴅᴇ ᴛᴀᴄᴏꜱ")
    input()
    print(a, ": This must be a cafeteria")
    input()
    print(a, ": This seems to been abandoned for years")
    input()
    print("You walked around the cafeteria and found different messeges in the walls")
    input()
    print("ᴇᴀᴛ ʜᴇᴀʟᴛʜʏ")
    input()
    print("ᴛʜɪꜱ ɪꜱ ᴀʟʟ ʏᴏᴜʀ ꜰᴀᴜʟᴛ")
    input()
    print("What happened in this place?")
    input()
    print("???: Who are you?")
    print("Your turned your head to see a girl that is probably three years younger than you")
    input()
    print(a, ": My name is ", a, ", what are your doing here?")
    input()
    print("???: I just was walking to get back to my house and then all is in black, I just remember I woke here, by the way I am Luna")
    input()
    print("She seems a girl that is very serious")
    input()
    print("Luna : But, what are you doing here?")
    input()
    print(a, ": Just like you I don't know, I just remember my name ")
    input()
    print("Luna : That is interesting ")
    input()
    print("Luna: I think we should investigate this place a little bit more, to know what are we doing here")
    input()
    print("You two walk over the cafeteria searching for anything that could help you")
    input()
    print("Luna: I think we aren't going to find anything in here")
    input()
    print(a,": There must be something in here, this place can't be empty at all")
    input()
    print("Luna start walking to the entrence of the kitchen")
    input()
    print(a, ": CAREFUL LUNA!!!")
    input()
    print("Luna looks back at you witha confused face, in that moment you don't think anything at all")
    input()
    print("You run directly to the girl")
    input()
    print(a, ": MOVE!!!")
    input()
    print("You grab Luna by the arm at pull her to one side")
    input()
    print("At the same moment a part of the roof falls just besides you")
    input()
    print("Luna: You saved me, why?")
    input()
    print(a, ": I couldn't let my adventure friend get hurt")
    input()
    print("Luna: Adventure friend? ")
    input()
    print(a, ": Hey this is like an adventure and we are here together so....")
    input()
    print("Luna: mmmmm I like it")
    input()
    print(
        "She said it with a smile, the first time you had seen in her face, you immediately return the smile"
    )
    input()
    print(
        "Luna: I wonder how many years this has been abondoned? , what happened to this place?, what....."
    )
    input()
    print("At that momnet you interrupt her")
    input()
    print(a, ": I think is better if we do not ask to many questions Luna")
    input()
    print(a, ": This place do not have the impression to have a pretty study")
if (y == "left"):
    print(a, ": I think I choose the left side, I really wanna get out")
    input()
    print("You follow the left corridor until you see the end of it")
    input()
    print("You see a classroom that has a sign in it")
    input()
    print("ᴛʜɪꜱ ɪꜱ ᴀʟʟ ʏᴏᴜʀ ꜰᴀᴜʟᴛ")
    input()
    b = input(
        "Do you want to open the door yes or no? (write in lower letters)")
    if (b == "yes"):
        print("You open the door")
        input()
        print(
            "You found a little girl sitting at the center of the room, she is staring to a wall of the classroom"
        )
        input()
        print(
            "The girl looked like she wasn´t paying attention to the world around her "
        )
        input()
        print(a, ": Hello?")
        input()
        print(a, ": umm ...... little girl")
        input()
        print(a, ": Can you hear me?")
        input()
        print(
            "After you said that the little girl seem to come back to the world around her"
        )
        input()
        print("???: Who are you?")
        input()
        print(a, ": I am ", a, ", and you are?")
        input()
        print("???: I am Luna")
        input()
        print(
            "This time that you have talked to her you didn´t see a single espresion in her face except for a serious face"
        )
        input()
        print(a, ": What are your doing here Luna?")
        input()
        print(
            "Luna: I don´t know, I just remember that I was walking home back from the school, and I woke up here a few minutes ago"
        )
        input()
        print("Luna: And ............ what about ......you?")
        input()
        print(a, ": I just remember my name")
        input()
        print("Luna: ..... are you searching for something?")
        input()
        print(
            a,
            ":  Well a girl name Emily said that I ahve to search for some documents"
        )
        input()
        print(
            "Luna: And you are just going to do it? Do you even know the girl or something?"
        )
        input()
        print(
            a,
            ": Well..... I trust her..... it is just that I think I have seen her before"
        )
        input()
        print("Luna: mmmm .... it is your decision at the end")
        input
        if (b == "no"):
            print("I don't want to open the door")
            input()
            print("You follow the corridor and turn right in a corner")
            input()
            print(
                "You continue walking until you see a door that has ᴅɪʀᴇᴄᴛᴏʀ´ꜱ ᴏꜰꜰɪᴄᴇ written in it"
            )
            input()
            print(a, ": This is were Emily wanted me to enter")
            input()
            print("You entered the office")
            input()
            print(a, ": There aren´t any documents in this place")
            input()
            print("You say after you search all over the place ")
            input()
            print("You found a security safe box")
            input()
            print("But you need to found the code")
            input()
            while True:
                print("For the first number, choose between 1 or 2")
                print("For the second number, choose between 6 or 9")
                print("For the third number, choose between 5 or 8")
                print("For the fourth number, choose between 4 or 0 ")
                num1 = int(input("Which is number 1?"))
                num2 = int(input("Which is number 2?"))
                num3 = int(input("Which is number 3?"))
                num4 = int(input("Which is number 4?"))
                if (num1 == 2 and num2 == 9 and num3 == 5 and num4 == 0):
                    print("That is correct that is the answer of the code")
                    break
                else:
                    print("Try again and read carrefully")
                print("You open the security box")
                input()
                print("You found documents inside")
                input()
                print(a, ": What is inside?")
                input()
                print(a, ": Knowimg this place it cant be something good")
                input()
                print(
                    "ꜰᴇʙʀᴜᴀʀʏ 18 2007, ᴇxᴘᴇʀɪᴍᴇɴᴛ 009. ᴛʜᴇ ᴇxᴘᴇʀɪᴍᴇɴᴛ ꜱᴇᴇᴍꜱ ᴛᴏ ʜᴀᴠᴇ ᴀ ɢᴏᴏᴅ ʀᴇꜱᴜʟᴛ ᴀᴛ ᴛʜᴇ ᴇɴᴅ ᴏꜰ ᴛʜᴇ ᴏʙꜱᴇʀᴠᴀᴛɪᴏɴ"
                )
                input()
                print(a, ": What is happening in this place?")
                input()
                print(
                    "You keep watching the documents that where in there, all the same talking some kind of experiment"
                )
                input()
                print("???: Hello?")
                input()
                print(
                    "You turned around quickly to know where the voice came from"
                )
                input()
                print(
                    "You found a little girl that has no expresion on her face except for a serious face"
                )
                input()
                print(a, ": Who are you?")
                input()
                print("???: I am Luna, and ...... you?")
                input()
                print(a, ": I am ", a, " , what are you doing here Luna?")
                input()
                print(
                    "Luna: I don´t know, I just remember that I was walking home back from the school, and I woke up here a few minutes ago"
                )
                input()
                print(a, ": That is weird, I don´t know how do I get here")
                input()
                print("Luna:..... mmmm...... ")
                input()
                print(a, " : How about if we go this way")
                input()
                print("Luna: You want me to go with you?")
                input()
                print(a, ": Well, I don't see why not")
                input()
                print("Luna: But, why?")
                print(a, ": I couldn't let my adventure friend get hurt")
    input()
    print("Luna: Adventure friend? ")
    input()
    print(a, ": Hey this is like an adventure and we are here together so....")
    input()
    print("Luna: mmmmm I like it")
    input()
    print(
        "She said it with a smile, the first time you had seen in her face, you immediately return the smile"
    )
